 const motivation = {
    grust: ['https://www.youtube.com/watch?v=pzIkI98CQtg',
        'https://www.youtube.com/watch?v=wE3svJxtND0',
        'https://youtu.be/EzqsZA9h9gI',
        'https://www.youtube.com/watch?v=4dPVEEO9e1I',
        "https://www.youtube.com/watch?v=KVy8pt9mdLw",
        'https://www.youtube.com/watch?v=Nb00PPY9qTI',
        'https://youtu.be/Z8dhwtSUNDc',
    ],
    podderjat: [
        'https://youtu.be/o7uDERvtqhc?t=11',
        'https://youtu.be/YVDRGWCdu2M',
        "https://youtu.be/X024jdU9HXM",
        'https://youtu.be/kydZE4U_jrg',
        'https://youtu.be/GEAYQpqQPy8?t=8',
        'https://youtu.be/0jFdzFz0Ato'

    ],
    osudit:['https://youtu.be/j-uBIraHNa4',
        'https://youtu.be/IYtVFNhDdVo',
        'https://youtu.be/Gbv90jOh92E',
        'https://youtu.be/pCbwXcVWjo8',
        'https://youtu.be/VvazFfEDPvU',
        'https://youtu.be/jaY7dn-57Fw',
        'https://youtu.be/YxjMJBQn-is',
        'https://youtu.be/KTITw8X2368',
        'https://youtu.be/Z8dhwtSUNDc',
        'https://youtu.be/KKWoF7LcAFA',
        'https://youtu.be/aA8rO_q4UG8',
        "https://youtu.be/6_qjqJMyM_4",
    ],
    ocenit_fu:['https://youtu.be/Gbv90jOh92E',
        'https://youtu.be/X024jdU9HXM',
        'https://youtu.be/qSkUuFySwqE',
        'https://youtu.be/iD2qECxI0Rk',
        'https://youtu.be/pCbwXcVWjo8',
        'https://youtu.be/xoMgnJDXd3k',
        'https://youtu.be/8-daMyeA8RE?t=16',
        'https://youtu.be/YxjMJBQn-is',
        'https://youtu.be/KTITw8X2368',
        'https://youtu.be/MGxAtO5n9SY',
        'https://youtu.be/Z8dhwtSUNDc',
        'https://youtu.be/6_qjqJMyM_4',
        'https://youtu.be/zIgo-j9rMtQ',
    ],
    ocenit_ok:['https://youtu.be/YVDRGWCdu2M',
        'https://youtu.be/qSkUuFySwqE',
        'https://youtu.be/W7SM23mlw6g',
        'https://youtu.be/1dRrE_ROot0',
        'https://www.youtube.com/watch?v=pxrqirsC-Zo',
    ],

}
 module.exports =  motivation
